version: 1.0.{build}

environment:
  my_variable:
    secure: sqA+VaENv6wi/JnGV4cJLJ+9DHqsGN3iHN8xWAKiXm/KgenHesOU5ra0gl973C17

build_script:
- cmd: >-
    git submodule init

    git submodule update

    ./bin/composer.bat config -g github-oauth.github.com %MY_VARIABLE%

    ./bin/composer.bat update
    
    mkdir artifacts

    git clone https://github.com/pmmp/PocketMine-DevTools --depth=1

    php -dphar.readonly=0 path/to/ConsoleScript.php --make src,vendor,resources --relative ./ --entry src/pocketmine/PocketMine.php --out artifacts/pmmpAPI4.phar

artifacts:
- path: artifacts/pmmpAPI4.phar
