version: 1.0.{build}

environment:
  my_variable:
    secure: sqA+VaENv6wi/JnGV4cJLJ+9DHqsGN3iHN8xWAKiXm/KgenHesOU5ra0gl973C17

build_script:
- cmd: >-
    git submodule init

    git submodule update

    
    rm -rf artifacts
    
    mkdir artifacts

    C:\projects\pmmp-4x\bin\php\php.exe -d disable_functions=chmod -dphar.readonly=0 PocketMine-DevTools\src\DevTools\ConsoleScript.php --make src,vendor,resources --relative ./ --entry src/pocketmine/PocketMine.php --out artifacts/steadfast2API3.phar

artifacts:
- path: artifacts/steadfast2API3.phar
