version: 1.0.{build}

environment:
  my_variable:
    secure: sqA+VaENv6wi/JnGV4cJLJ+9DHqsGN3iHN8xWAKiXm/KgenHesOU5ra0gl973C17

build_script:
- cmd: >-
    git submodule init

    git submodule update

    ./bin/composer.bat config -g github-oauth.github.com %MY_VARIABLE%

    ./bin/composer.bat update

    start.bat