name: MiRmUseful
version: 1.0.2
api: [4.0.0,3.0.0]
author: haniokasai
main: MiRmUseful\MainClass


commands:
  adminjoin:
    description: "AdminJoin main command"
    usage: "/AdminJoin <message on op entry>"
    permission: "adminjoin.command.adminjoin"

  banitem:
    description: "BanItem main command."
    permission: banitem.command.banitem
    usage: "/banitem <ban/unban/list> [ID[:Damage]]"

  oplist:
    description: "show op list."

  s:
    description: "プレイヤーの情報を調べます"
    usage: " /s [Player]…そのプレイヤーのip を調べます"

  idc:
    usage: "idchecker"

  xyz:
    description: Returns Player Coordinates
    usage: "/xyz"
    permission: xyz.command.xyz

  ri:
    description: "インベントリのItemを全消去します"

permissions:
  adminjoin:
    default: op
    description: "Allows ops to use the AdminJoin command"
    children:
      alias.command:
        default: op
        description: "Allows ops to use the AdminJoin command"
        children:
          alias.command.alias:
            default: op
            description: "Allows changing of the join message"

  banitem:
    default: false
    description: "Allows access to all BanItem features."
    children:
      banitem.bypass:
        default: false
        description: "Allows access to using banned items."
      banitem.command:
        default: false
        description: "Allows access to all BanItem commands."
        children:
          banitem.command.banitem:
            default: op
            description: "Allows access to the item command."

  s:
    default:  op
    description: "Allows using all the ip things"
    children:
      s.command:
        default: op
        description: "Allows using all the ip commands"
