version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-demo-java-spring # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/php:7.2-cli-node-browsers-legacy # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # special step to check out source code to working directory
      - run: pecl install channel://pecl.php.net/pthreads-3.1.6
      - run: echo | pecl install channel://pecl.php.net/yaml-2.0.2
      - run: pecl install channel://pecl.php.net/crypto-0.3.1
      - run: git clone https://github.com/pmmp/pthreads.git
      - run: cd pthreads
      - run: git checkout c8cfacda84f21032d6014b53e72bf345ac901dac
      - run: phpize
      - run: ./configure
      - run: phpize
      - run: make
      - run: make install
      - run: cd ..
      - run: echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      - run: composer install
      
      - store_artifacts: # store the uberjar as an artifact
          path: target
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    
